// <auto-generated />
namespace Aquarius.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Cryptos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cryptos));
        
        string IMigrationMetadata.Id
        {
            get { return "202012162028469_Cryptos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
