// <auto-generated />
namespace Aquarius.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class setTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131825112_setTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
