// <auto-generated />
namespace Aquarius.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SaleTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131831262_SaleTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
